- task: DockerCompose@0
  displayName: Run a Docker Compose command
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: '$(azureSubscriptionEndpoint)'
    azureContainerRegistry: '$(azureContainerRegistry)'
    dockerComposeFile: 'docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'rm'